Demo/Demo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from Home import views as Home_views
urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^account/',include("account.urls")),
    url(r'^pwd_reset/',include("password_reset.urls",namespace="pwd_reset",app_name="pwd_reset")),
    url(r'^BlogPost/',include("BlogPost.urls")),# import the BlogPost app
    url(r'^home/',Home_views.index,name="index"),
    url(r'^Article/',include("Articleapp.urls",namespace="Articleapp",app_name="Articleapp")),
    url(r'^Comment/',include("comment.urls")),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Demo/Home/urls.py
from . import views as Home_views
from django.conf.urls import url

app_name = "Home"
#The main resolution

urlpatterns = [

]

Demo/account/urls.py
from django.conf.urls import url
from . import views as account_views
from django.contrib.auth import views as auth_views
app_name = "account"

urlpatterns = [
    url(r'^activate/(?P<activate_code>.*)/$',account_views.ActivateUser,name="ActivateUser"),
    url(r'^register/$',account_views.register,name="register"),
    url(r'^login/$',auth_views.login,{"template_name":"account/login.html"},name="login"),
    url(r'^logout/$',auth_views.logout,{"template_name":"account/logout.html"},name="logout"),
    url(r'^password-change/$',auth_views.password_change,{"template_name":"account/password_change.html","post_change_redirect":"/account/password-change-done"},name="password_change"),
    url(r'^password-change-done/$',auth_views.password_change_done,{"template_name":"account/password_change_done.html"},name="password_change_done"),
    url(r'^AuthorArticle/(?P<user_id>\d+)/$',account_views.AuthorArticle,name="AuthorArticle"),
]

Demo/Home/models.py
from django.db import models

# Create your models here.

Demo/Home/views.py
from django.shortcuts import render,get_object_or_404
from BlogPost.models import Post,Column
from account.models import Userprofile
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
# Create your views here.

def index(request):
    Articles = Post.objects.all().order_by("-publish_time","title")
    paginator = Paginator(Articles,8)
    page = request.GET.get('page')
    UserlikesMoreArticle = Post.objects.all().order_by("-users_like")[:5]
    UserReadsMoreArticle= Post.objects.all().order_by("-users_read")[:5]
    columns = Column.objects.all()
    try:
        current_page = paginator.page(page)
        articles = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        articles = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        articles = current_page.object_list
    return render(request,"Home/Home.html",{"Articles":articles,"page":current_page,"UserlikesMoreArticle":UserlikesMoreArticle,"UserReadsMoreArticle":UserReadsMoreArticle,
                                            "Column":columns})

Demo/templates/Home/Home.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Programmer</title>
    <!-- 新 Bootstrap4 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/css/bootstrap.min.css">

    <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>

    <!-- popper.min.js 用于弹窗、提示、下拉菜单 -->
    <script src="https://cdn.staticfile.org/popper.js/1.12.5/umd/popper.min.js"></script>

    <!-- 最新的 Bootstrap4 核心 JavaScript 文件 -->
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/js/bootstrap.min.js"></script>

    <!-- 引入字体图标文件 -->
    <link rel="stylesheet" href="https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css">

    <!-- 引用自己的Css -->
    <link rel="stylesheet" href="{% static 'css/StyleCss.css' %}">

    <!-- swifter 插件文件-->
    <link rel="stylesheet" href="{% static 'dist/css/swiper.min.css' %}">
    <script src="{% static 'dist/js/swiper.min.js' %}"></script>
    <!-- -->
    <style>
        body {
            background-color: #FAFAFA;
        }
    </style>
</head>
<body>
<div class="container-fluid text-center">
    {% include "nav3.html" %}
</div>
<div class="container text-center" style="margin-top:5px;background-color: white;">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-9">
            <div class="swiper-container" style="height: 400px">
                <div class="swiper-wrapper">
                    <div class="swiper-slide"><img src="{% static 'Image/BackGround.Jpg' %}" width="100%" height="100%">
                    </div>
                    <div class="swiper-slide"><img src="{% static 'Image/logo.png' %}" width="100%" height="100%"></div>
                </div>
                <!-- 如果需要分页器 -->
                <div class="swiper-pagination"></div>

                <!-- 如果需要导航按钮 -->
                <div class="swiper-button-prev"></div>
                <div class="swiper-button-next"></div>

                <!-- 如果需要滚动条 -->
                <div class="swiper-scrollbar"></div>
            </div>
            <div class="ArticleList">
                <h5 class="text-left">最新发布</h5>
                {% for article in Articles %}
                {% with total_likes=article.users_like.count %}
                {% with total_read=article.users_read.count %}
                <a href="{{ article.get_detail_url }}" style=" text-decoration:none;">
                    <div class="Article text-left">
                        <h4 style="color:black;">{{ article.title }}</h4>
                        <div class="author_time">
                            {% if user.is_authenticated %}
                            <span><a href="{% url 'account:AuthorArticle' article.author.id %}">{{ article.author.username }}</a> </span>
                            | <span><a href="#">{{ article.publish_time|date }}</a>
                             <span class="fa fa-thumbs-up" style="margin-left:20px;color:green;">{{ total_likes }} like{{ total_likes | pluralize }}</span>
                              <span class="fa fa-eye" style="margin-left:20px;color:green;">{{ total_read }} like{{ total_read | pluralize }}</span></span>
                            | <span><a href="#">{{ article.column }}</a> </span>
                            {% else %}
                            <span><a href="javascript:" onclick="you_should_login()">{{ article.author.username }}</a> </span>
                            | <span><a href="#">{{ article.publish_time|date }}</a> </span>
                            | <span><a href="#">{{ article.column }}</a> </span>
                            <span class="fa fa-thumbs-up" style="margin-left:20px;color:green;">{{ total_likes }} like{{ total_likes | pluralize }}</span>
                            <span class="fa fa-eye" style="margin-left:20px;color:green;">{{ total_read }} like{{ total_read | pluralize }}</span></span>
                            {% endif %}
                        </div>
                        <div class="abstract">
                            <p>{{ article.abstract }}</p>
                            <hr>
                        </div>
                    </div>
                </a>
                {% endwith %}
                {% endwith %}
                {% empty %}
                <div>暂时还没有文章发布~</div>
                {% endfor %}
                {% include "paginator.html" %}
                <div class="text-center MoreArticle">
                    <a href="#"><p>更多</p></a>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-12 col-12 Rightside border">
            <div class="OtherArea text-left">
                <h5><span class="fa fa-blind"></span>点赞最多的文章</h5>
                <ul>
                    {% for item in UserlikesMoreArticle %}
                    <a href="{{ item.get_detail_url }}">
                        <li>{{ item.title }}
                            <p><span class="fa fa-thumbs-up">{{ item.users_like.count}} like{{ item.users_like.count| pluralize}}</span>
                            </p>
                        </li>
                    </a>
                    　{% endfor %}
                </ul>
                <hr>
            </div>
            <div class="OtherArea text-left">
                <h5><span class="fa fa-blind"></span>阅读最多的文章</h5>
                <ul>
                    {% for item in UserReadsMoreArticle %}
                    <a href="{{ item.get_detail_url }}">
                        <li>{{ item.title }}
                            <p><span class="fa fa-eye">{{ item.users_read.count}} read{{ item.users_read.count| pluralize}}</span>
                            </p>
                        </li>
                    </a>
                    　{% endfor %}
                </ul>
                <hr>
            </div>
            <div class="OtherArea text-left">
                <h5><span class="fa fa-blind"></span>栏目</h5>
                <div>
                    {% for item in Column %}
                    <button class="btn btn-primary btn-lg" style="color:white;margin:10px;">{{ item.column }}</button>
                    {% endfor %}
                </div>
                <hr>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
<script>
    var swiper = new Swiper('.swiper-container', {
        spaceBetween: 30,
        centeredSlides: true,
        loop: true,
        autoplay: {
            delay: 2500,
            disableOnInteraction: false,
        },
        pagination: {
            el: '.swiper-pagination',
            clickable: true,
        },
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },
    });
    function you_should_login() {
        layer.msg("登录后查看更多文章噢~");
    }
</script>
</body>
</html>