Demo/BlogPost/urls.py
from django.conf.urls import url
from . import views as BlogPost_views

app_name = "BlogPost"

urlpatterns = [
    url(r'^PostManage/$',BlogPost_views.PostManage,name="PostManage"),
    url(r'^ColumnManage/$',BlogPost_views.ColumnManage,name="ColumnManage"),
    url(r'^ColumnEdit/$',BlogPost_views.ColumnEdit,name="ColumnEdit"),
    url(r'^ColumnDel/$',BlogPost_views.ColumnDel,name="ColumnDel"),
    url(r'^article-post/$',BlogPost_views.PostArticle,name="PostArticle"),
    url(r'^delete-post/$',BlogPost_views.delete_post,name="delete_post"),
    url(r'^Post_detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',BlogPost_views.Post_detail,name="Post_detail"),
    url(r'^edit_post/(?P<post_id>\d+)/$',BlogPost_views.edit_post,name="edit_post"),
    url(r'^PersonalInformations/$',BlogPost_views.PersonalInformations,name="PersonalInformations"),
    url(r'^EditInformations/$',BlogPost_views.EditInformations,name="EditInformations"),
    url(r'^MyselfComments/$',BlogPost_views.MyComment,name="MyComment"),
    url(r'^deleteComment/$',BlogPost_views.deleteComment,name="deleteComment"),

]

Demo/Demo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from Home import views as Home_views
urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^account/',include("account.urls")),
    url(r'^pwd_reset/',include("password_reset.urls",namespace="pwd_reset",app_name="pwd_reset")),
    url(r'^BlogPost/',include("BlogPost.urls")),# import the BlogPost app
    url(r'^home/',Home_views.index,name="index"),
    url(r'^Article/',include("Articleapp.urls",namespace="Articleapp",app_name="Articleapp")),
    url(r'^Comment/',include("comment.urls")),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Demo/account/urls.py
from django.conf.urls import url
from . import views as account_views
from django.contrib.auth import views as auth_views
app_name = "account"

urlpatterns = [
    url(r'^activate/(?P<activate_code>.*)/$',account_views.ActivateUser,name="ActivateUser"),
    url(r'^register/$',account_views.register,name="register"),
    url(r'^login/$',auth_views.login,{"template_name":"account/login.html"},name="login"),
    url(r'^logout/$',auth_views.logout,{"template_name":"account/logout.html"},name="logout"),
    url(r'^password-change/$',auth_views.password_change,{"template_name":"account/password_change.html","post_change_redirect":"/account/password-change-done"},name="password_change"),
    url(r'^password-change-done/$',auth_views.password_change_done,{"template_name":"account/password_change_done.html"},name="password_change_done"),
    url(r'^AuthorArticle/(?P<user_id>\d+)/$',account_views.AuthorArticle,name="AuthorArticle"),
]

Demo/BlogPost/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils import timezone
from slugify import slugify
# Create your models here.

class Column(models.Model):
    column = models.CharField(max_length=30)
    user = models.ForeignKey(User,related_name="user_column")
    created_time = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.column


class Post(models.Model):

    title = models.CharField(max_length=40)
    body = models.TextField()
    author = models.ForeignKey(User,related_name="UserPost")
    column = models.ForeignKey(Column,related_name="Pospt_Column",default='')
    abstract = models.CharField(max_length=200,null=True)
    publish_time = models.DateTimeField(auto_now_add=True)
    modify_time = models.DateField(auto_now=True)
    slug = models.SlugField(max_length=500,blank=True)
    users_like = models.ManyToManyField(User,related_name="articles_like",blank=True)
    users_read = models.ManyToManyField(User,related_name="artilces_read",blank=True)

    def __str__(self):
        return "%s-%s" % (self.author.username,self.title)

    def save(self,*args,**kwargs):
        self.slug = slugify(self.title)
        self.abstract = "  "  + self.body[:190]
        self.abstract += ".."
        super(Post,self).save(*args,**kwargs)
    def get_absolute_url(self):
        return reverse("BlogPost:Post_detail",args=[self.id,self.slug])

    def get_detail_url(self):
        return reverse("Articleapp:ArticleDetail",args=[self.id,self.slug])

    class Meta:
        ordering = ("-publish_time","title")
        index_together = (("id","slug"),)

Demo/account/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Userprofile(models.Model):

    motto = models.TextField(blank=True)
    HeadImage = models.ImageField(upload_to="Image/%Y/%m/%d",blank=True)
    WeCheat = models.ImageField(upload_to="WeCheat/%Y/%m/%d",blank=True)
    phone = models.CharField(max_length=11,blank=True)
    user = models.OneToOneField(User,related_name="user_profile")
    School = models.CharField(max_length=20,blank=True)
    def __str__(self):
        return "{}-profile".format(self.user.username)

class EmailVerifyRecord(models.Model):
    code = models.CharField(max_length=20,verbose_name="验证码")
    email = models.CharField(max_length=50,verbose_name="邮箱")
    send_time = models.DateTimeField(verbose_name="发送时间",auto_now_add=True)
    class Meta:
        verbose_name = u"邮箱验证码"
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{}({})'.format(self.code,self.email)

Demo/BlogPost/forms.py
from .models import Post,Column
from django import forms

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("title","body")

class ColumnForm(forms.ModelForm):
    class Meta:
        model = Column
        fields = ("column",)

Demo/BlogPost/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from .forms import PostForm,ColumnForm
from .models import Post,Column
from account.models import Userprofile
from account.forms import UserprofileForm
from django.http import HttpResponse,HttpResponseRedirect
from comment.models import Comments
# Create your views here.

@login_required(login_url='/account/login/')
@csrf_exempt
def ColumnManage(request):
    if request.method == "GET":
        columns = Column.objects.filter(user=request.user)
        column_form = ColumnForm()
        return render(request,"BlogPost/Column.html",{"columns":columns,"column_form":column_form})
    if request.method == "POST":
        column_name = request.POST['column']
        columns = Column.objects.filter(column=column_name)
        if columns:
            return HttpResponse("2")
        else:
            Column.objects.create(user=request.user,column=column_name)
            return HttpResponse("1")


@login_required(login_url='/account/login/')
@csrf_exempt
@require_POST
def ColumnEdit(request):
    column_id = request.POST['column_id']
    column_name = request.POST['column_name']
    try:
        Line = Column.objects.get(id=column_id)
        Line.column = column_name
        Line.save()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

@login_required(login_url='/account/login/')
@csrf_exempt
@require_POST
def ColumnDel(request):
    column_id = request.POST['column_id']
    try:
        Line = Column.objects.get(id=column_id)
        Line.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

@login_required(login_url='/account/login/')
def PostManage(request):
    Posts = Post.objects.filter(author=request.user)
    return render(request,"BlogPost/Post.html",{"Posts":Posts})

@login_required(login_url='/account/login/')
@csrf_exempt
def PostArticle(request):
    if request.method == "POST":
        article_post_form = PostForm(data=request.POST)
        if article_post_form.is_valid():
            cd = article_post_form.cleaned_data
            try:
                new_article = article_post_form.save(commit=False)
                new_article.author = request.user
                new_article.column = Column.objects.get(id=request.POST['column_id'])
                new_article.save()
                return HttpResponse("1")
            except:
                return  HttpResponse("2")
        else:
            return  HttpResponse("3")
    else:
        article_post_form = PostForm()
        article_columns = Column.objects.all()
        return render(request,"BlogPost/ArticlePost.html",{"article_post_form":article_post_form,"article_columns":article_columns})

@login_required(login_url='/account/login/')
@require_POST
@csrf_exempt
def delete_post(request):
    post_id = request.POST['post_id']
    try:
        post = Post.objects.get(id=post_id)
        post.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

def Post_detail(request,id,slug):
    post = get_object_or_404(Post,id=id,slug=slug)
    return render(request,"BlogPost/PostDetail.html",{"post":post})

@login_required(login_url='/account/login')
@csrf_exempt
def edit_post(request,post_id):
    if request.method == "GET":
        columns = Column.objects.all()
        article = Post.objects.get(id=post_id)
        article_form = PostForm(initial={"title":article.title})
        this_article_column = article.column
        return render(request,"BlogPost/edit_post.html",{"columns":columns,"article":article,"article_form":article_form,"this_article_column":this_article_column})
    if request.method == "POST":
        article = Post.objects.get(id=post_id)
        try:
            column = request.POST['column']
            title = request.POST['title']
            body = request.POST['body']
            article.column = Column.objects.get(id=column)
            article.title = title
            article.body = body
            article.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")
@login_required(login_url='/account/login/')
@csrf_exempt
def PersonalInformations(request):
    userprofile = Userprofile.objects.get(user=request.user)
    Articles = Post.objects.filter(author=request.user)
    return render(request,"BlogPost/PersonalInformations.html",{"userprofile":userprofile,"Articles":Articles})

def EditInformations(request):
    if request.method == "GET":
        userprofile = Userprofile.objects.get(user=request.user)
        return render(request,"BlogPost/EditInformations.html",{"userprofile":userprofile})
    if request.method == "POST":
        try:
            motto = request.POST['motto']
            school = request.POST['school']
            phone = request.POST['phone']
            userprofile = Userprofile.objects.get(user=request.user)
            userprofile.motto = motto
            userprofile.School = school
            userprofile.phone = phone
            userprofile.save()
            return HttpResponse("1")
        except:
            return HttpResponse("2")

@login_required(login_url='/account/login/')
@csrf_exempt
def MyComment(request):
    AllPost = Post.objects.all()
    comments = []
    for post in AllPost:
        comments += Comments.objects.filter(Comment_article=post)
    return render(request,"BlogPost/MyselfComment.html",{"comments":comments})

@login_required(login_url='/account/login/')
@csrf_exempt
@require_POST
def deleteComment(request):
    comment_id = request.POST['comment_id']
    try:
      #  print(comment_id)
        comment = Comments.objects.get(id=comment_id)
        comment.delete()
        return HttpResponse("1")
    except:
        return HttpResponse("2")

Demo/templates/BlogPost/ArticlePost.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %} 文章管理 {% endblock %}
{% block Style %}
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
{% endblock %}
{% block header %}
<nav class="navbar navbar-expand-sm bg-dark">
  <ul class="navbar-nav text-center" style="width:100%;">
    <li class="nav-item">
        <a href="/home"><img src="{% static 'Image/logo.png' %}" class="rounded-circle" width="40%"> </a>
    </li>
      <li class="nav-item dropdown">
           <button class="btn btn-primary bg-white nav-link dropdown-toggle" data-toggle="dropdown" style="margin:0 auto;color:black;font-family: 华文新魏;font-size:1.2rem;">{{ user.username }}</button>
          <div class="dropdown-menu text-center">
              <a class="dropdown-item" href="{% url 'account:password_change' %}">修改密码</a>
              <a class="dropdown-item" href="{% url 'account:logout' %}">退出登陆</a>
              <a class="dropdown-item" href="{% url 'BlogPost:PostManage' %}">后台管理</a>
              <!--<a class="dropdown-item" href="#" onclick="functionDoesNotbuild()">个人信息</a>-->
          </div>
       </li>
    <li class="nav-item">
      <a class="nav-link" href="/home"><p>首页</p></a>
    </li>
   <li class="nav-item">
      <a class="nav-link" href="{% url 'BlogPost:PostManage' %}"><p>文章管理</p></a>
    </li>
       <li class="nav-item">
      <a class="nav-link" href="{% url 'BlogPost:ColumnManage' %}"><p>栏目管理</p></a>
    </li>
       <li class="nav-item">
      <a class="nav-link" href="{% url 'BlogPost:PersonalInformations' %}"><p>个人信息</p></a>
    </li>
       <!--<li class="nav-item">-->
      <!--<a class="nav-link" href="{% url 'BlogPost:MyComment' %}"><p>我的评论</p></a>-->
    <!--</li>-->
    <li class="nav-item">
      <a class="nav-link" href="javascript:" onclick="functionDoesNotbuild()"><p>美图页面</p></a>
    </li>
  </ul>

</nav>

{% endblock %}
{% block content %}

<div class="StylePosition">
    <form>
        <div class="row text-left group">
            <div class="col-12 col-sm-12 col-md-1 "><span>标题:</span></div>
            <div class="col-12 col-sm-12 col-md-3">{{ article_post_form.title }}</div>
        </div>
        <div class="row text-left group">
            <div class="col-12 col-sm-12 col-md-1 "><span>栏目:</span></div>
            <div class="col-12 col-sm-12 col-md-3">
                <select id="which_column">
                    {% for column in article_columns %}
                    <option value="{{ column.id }}">{{ column.column }}</option>
                    {% endfor %}
                </select>
            </div>
                 <div class="col-12 col-sm-12 col-md-4"><button type="button" onclick="add_column()">增加栏目</button></div>
        </div>
        <div class="row form-group text-left group">
            <div class="col-12 col-sm-12 col-md-1"><span>内容:</span></div>
            <div  id="editormd" class="col-12 col-sm-12 col-md-11">
                <textarea id="id_body" style="display:none"></textarea>
            </div>
        </div>
           <div class="row text-left group">
                <div class="col-12 col-sm-12 col-md-1"></div>
            <input type="button" class="btn btn-primary btn-lg" value="发布文章" onclick="publish_article()">
        </div>

    </form>

</div>

<script type="text/javascript" src="{% static 'js/csrf.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript" src="{% static 'js/OwnCss.js' %}"></script>
<script type="text/javascript" src="{% static 'editor/editormd.min.js' %}"></script>
<script type="text/javascript">
    $(function () {
        var editor=editormd("editormd",{
            width:"100%",
            height:640,
            syncScrolling:"single",
            path: "{% static 'editor/lib/' %}",
            emoji:true
        });
    });


function add_column(){
        var index = layer.open({
            type:1,
            skin:"layui-layer-rim",
            area:["400px","200px"],
            content:'<div class="text-center"><p>请输入栏目名称</p><p><input id="id_column"></p></div>',
            btn:['确定','取消'],
            btnAlign:"c",
            yes:function (index,layero) {
                column_name = $('#id_column').val();
                console.log(column_name);
                $.ajax({
                    url:"{% url 'BlogPost:ColumnManage' %}",
                    data:{"column":column_name},
                    type:"POST",
                    success:function (e) {
                        if (e=="1"){
                            layer.msg("增加栏目成功");
                            parent.location.reload();
                        }
                        else{
                            layer.msg("此栏目已有,请更换名称.");
                        }
                    },
                });
            },
            btn2:function (index,layero) {
                layer.close(index);
            }
        });
    }

</script>
{% endblock %}

Demo/templates/BlogPost/Post.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %} 文章管理 {% endblock %}

{% block header %}
<nav class="navbar navbar-expand-sm bg-dark">

  <ul class="navbar-nav text-center" style="width:100%;">
    <li class="nav-item">
        <a href="/home"><img src="{% static 'Image/logo.png' %}" class="rounded-circle" width="40%"> </a>
    </li>
      <li class="nav-item dropdown">
           <button class="btn btn-primary bg-white nav-link dropdown-toggle" data-toggle="dropdown" style="margin:0 auto;color:black;font-family: 华文新魏;font-size:1.2rem;">{{ user.username }}</button>
          <div class="dropdown-menu text-center">
              <a class="dropdown-item" href="{% url 'account:password_change' %}">修改密码</a>
              <a class="dropdown-item" href="{% url 'account:logout' %}">退出登陆</a>
             <a class="dropdown-item" href="{% url 'BlogPost:PostManage' %}">后台管理</a>
              <!--<a class="dropdown-item" href="#" onclick="functionDoesNotbuild()">个人信息</a>-->
          </div>
       </li>
<li class="nav-item">
      <a class="nav-link" href="/home"><p>首页</p></a>
    </li>
   <li class="nav-item">
      <a class="nav-link" href="{% url 'BlogPost:PostManage' %}"><p>文章管理</p></a>
    </li>
       <li class="nav-item">
      <a class="nav-link" href="{% url 'BlogPost:ColumnManage' %}"><p>栏目管理</p></a>
    </li>
      <li class="nav-item">
      <a class="nav-link" href="{% url 'BlogPost:PersonalInformations' %}"><p>个人信息</p></a>
    </li>
       <li class="nav-item">
      <a class="nav-link" href="{% url 'BlogPost:MyComment' %}"><p>我的评论</p></a>
    </li>
       <!--<li class="nav-item">-->
      <!--<a class="nav-link" href="javascript:" onclick="personInformation()"><p>个人信息</p></a>-->
    <!--</li>-->
    <li class="nav-item">
      <a class="nav-link" href="javascript:" onclick="functionDoesNotbuild()"><p>美图页面</p></a>
    </li>
  </ul>

</nav>

{% endblock %}
{% block content %}
<div class="row my-content">
<div class="left-side col-5 col-sm-5 col-md-2"  style="margin:10px">
    <ul class="nav flex-column">
    <li class="nav-item text-center">
      <a class="nav-link disabled" href="#">文章管理</a>
    </li>
  </ul>
</div>
<div class="PostManage col-5 col-sm-5 col-md-9"style="margin:10px">
        <a href="{% url 'BlogPost:PostArticle' %}"><p class="text-right"><button class="btn btn-primary">新增文章</button> </a></p>
</div>
</div>
<div class="row">
    <div class="col-md-2" style="margin:10px">
    </div>
    <div class="col-12 col-sm-12 col-md-9" style="margin:10px">
        <table class="table table-hover">
            <tr>
                <td>序号</td>
                <td>文章名称</td>
                <td>发表时间</td>
                <td>栏目</td>
                <td>操作</td>
            </tr>
            {% for Post in Posts %}
            <tr>
                <td>{{ forloop.counter}}</td>
                <td><a href="{{ Post.get_absolute_url }}">{{ Post.title }}</a></td>
                <td>{{ Post.publish_time }}</td>
                <td>{{ Post.column.column }}</td>
                <td>
                   <a href="{% url 'BlogPost:edit_post' Post.id %}" name="edit"  style="color:black;font-size:1.2rem;margin-right: 4px;"> <span class="fa fa-pencil-square"></span></a>
                   <a href="javascript:" name="delete" onclick="delete_post(this,{{ Post.id }})" style="color:black;font-size:1.2rem;margin-left:4px;"> <span class="fa fa-trash"></span></a></td>
            </tr>
            {% empty %}
            <p>赶紧发表你的第一篇文章吧~</p>
            {% endfor %}
        </table>
    </div>
</div>
<script type="text/javascript" src="{% static 'js/csrf.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/OwnCss.js' %}"></script>
<script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript">
    function delete_post(the,post_id) {
        var title= $(the).parents("tr").children("td").eq(1).text();
        console.log(title);
        var index = layer.open({
            type:1,
            skin:"layui-layer-rim",
            area:["400px","150px"],
            title:"删除文章",
            content:"<div class='text-center'><p>是否确定删除文章?</p></div>",
            btn:['确定','取消'],
            yes:function () {
                $.ajax({
                    type:"POST",
                    data:{"post_id":post_id},
                    url:"{% url 'BlogPost:delete_post' %}",
                    success:function (e) {
                        if (e=="1"){
                            parent.location.reload();
                            layer.msg("删除成功");
                        }
                        else{
                            layer.msg("删除失败");
                        }
                    },
                });
            },
        });
    }
</script>
{% endblock %}

Demo/templates/BlogPost/edit_post.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %} 文章管理 {% endblock %}
{% block Style %}
<link rel="stylesheet" href="{% static 'editor/css/style.css' %}">
<link rel="stylesheet" href="{% static 'editor/css/editormd.css' %}">
{% endblock %}
{% block header %}
<nav class="navbar navbar-expand-sm bg-dark">
  <ul class="navbar-nav text-center" style="width:100%;">
    <li class="nav-item">
        <a href="/home"><img src="{% static 'Image/logo.png' %}" class="rounded-circle" width="40%"> </a>
    </li>
      <li class="nav-item dropdown">
           <button class="btn btn-primary bg-white nav-link dropdown-toggle" data-toggle="dropdown" style="margin:0 auto;color:black;font-family: 华文新魏;font-size:1.2rem;">{{ user.username }}</button>
          <div class="dropdown-menu text-center">
              <a class="dropdown-item" href="{% url 'account:password_change' %}">修改密码</a>
              <a class="dropdown-item" href="{% url 'account:logout' %}">退出登陆</a>
             <a class="dropdown-item" href="{% url 'BlogPost:PostManage' %}">后台管理</a>
              <!--<a class="dropdown-item" href="#" onclick="functionDoesNotbuild()">个人信息</a>-->
          </div>
       </li>
 <li class="nav-item">
      <a class="nav-link" href="/home"><p>首页</p></a>
    </li>
   <li class="nav-item">
      <a class="nav-link" href="{% url 'BlogPost:PostManage' %}"><p>文章管理</p></a>
    </li>
       <li class="nav-item">
      <a class="nav-link" href="{% url 'BlogPost:ColumnManage' %}"><p>栏目管理</p></a>
    </li>
       <li class="nav-item">
      <a class="nav-link" href="{% url 'BlogPost:PersonalInformations' %}"><p>个人信息</p></a>
    </li>
       <li class="nav-item">
      <a class="nav-link" href="{% url 'BlogPost:MyComment' %}"><p>我的评论</p></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="javascript:" onclick="functionDoesNotbuild()"><p>美图页面</p></a>
    </li>

  </ul>

</nav>

{% endblock %}
{% block content %}

<div class="StylePosition">
    <form action="." method="post">
        {% csrf_token %}
        <div class="row text-left group">
            <div class="col-12 col-sm-12 col-md-1 "><span>标题:</span></div>
            <div class="col-12 col-sm-12 col-md-3">{{ article_form.title }}</div>
        </div>
        <div class="row text-left group">
            <div class="col-12 col-sm-12 col-md-1 "><span>栏目:</span></div>
            <div class="col-12 col-sm-12 col-md-3">
                <select id="which_column">
                    {% for column in columns %}
                    {% if column == this_article_column %}
                    <option selected="selected" value="{{ column.id }}">{{ column.column }}</option>
                    {% else %}
                    <option value="{{ column.id }}">{{ column.column }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
            </div>
                 <div class="col-12 col-sm-12 col-md-4"><button type="button" onclick="add_column()">增加栏目</button></div>
        </div>
        <div class="row form-group text-left group">
            <div class="col-12 col-sm-12 col-md-1"><span>内容:</span></div>
            <div  id="editormd" class="col-12 col-sm-12 col-md-11">
                <textarea id="id_body" style="display:none">{{ article.body }}</textarea>
            </div>
        </div>
           <div class="row text-left group">
                <div class="col-12 col-sm-12 col-md-1"></div>
            <input type="button" class="btn btn-primary btn-lg" value="提交修改" onclick="edit_post()">
        </div>

    </form>

</div>

<script type="text/javascript" src="{% static 'js/csrf.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript" src="{% static 'js/OwnCss.js' %}"></script>
<script type="text/javascript" src="{% static 'editor/editormd.min.js' %}"></script>
<script type="text/javascript">
     $(function () {
        var editor=editormd("editormd",{
            width:"100%",
            height:640,
            syncScrolling:"single",
            path: "{% static 'editor/lib/' %}",
            emoji:true,
        });
    });

     function edit_post() {
         var title=$("#id_title").val();
         var body=$("#id_body").val();
         var column=$("#which_column").val();
         $.ajax({
             type:"POST",
             data:{"title":title,"body":body,"column":column},
             url:"{% url 'BlogPost:edit_post' article.id %}",
             success:function (e) {
                 if　(e=="1"){
                     layer.msg("修改成功！");
                     window.location.href="{% url 'BlogPost:PostManage' %}";
                 }
                 else{
                     layer.msg("修改失败");
                 }
             },
         });
     }

function add_column(){
        var index = layer.open({
            type:1,
            skin:"layui-layer-rim",
            area:["400px","200px"],
            content:'<div class="text-center"><p>请输入栏目名称</p><p><input id="id_column"></p></div>',
            btn:['确定','取消'],
            btnAlign:"c",
            yes:function (index,layero) {
                column_name = $('#id_column').val();
                console.log(column_name);
                $.ajax({
                    url:"{% url 'BlogPost:ColumnManage' %}",
                    data:{"column":column_name},
                    type:"POST",
                    success:function (e) {
                        if (e=="1"){
                            layer.msg("增加栏目成功");
                            parent.location.reload();
                        }
                        else{
                            layer.msg("此栏目已有,请更换名称.");
                        }
                    },
                });
            },
            btn2:function (index,layero) {
                layer.close(index);
            }
        });
    }
</script>
{% endblock %}