Demo/BlogPost/urls.py
from django.conf.urls import url
from . import views as BlogPost_views

app_name = "BlogPost"

urlpatterns = [
    url(r'^PostManage/$',BlogPost_views.PostManage,name="PostManage"),
    url(r'^ColumnManage/$',BlogPost_views.ColumnManage,name="ColumnManage"),
    url(r'^ColumnEdit/$',BlogPost_views.ColumnEdit,name="ColumnEdit"),
    url(r'^ColumnDel/$',BlogPost_views.ColumnDel,name="ColumnDel"),
    url(r'^article-post/$',BlogPost_views.PostArticle,name="PostArticle"),
    url(r'^delete-post/$',BlogPost_views.delete_post,name="delete_post"),
    url(r'^Post_detail/(?P<id>\d+)/(?P<slug>[-\w]+)/$',BlogPost_views.Post_detail,name="Post_detail"),
    url(r'^edit_post/(?P<post_id>\d+)/$',BlogPost_views.edit_post,name="edit_post"),
    url(r'^PersonalInformations/$',BlogPost_views.PersonalInformations,name="PersonalInformations"),
    url(r'^EditInformations/$',BlogPost_views.EditInformations,name="EditInformations"),
    url(r'^MyselfComments/$',BlogPost_views.MyComment,name="MyComment"),
    url(r'^deleteComment/$',BlogPost_views.deleteComment,name="deleteComment"),

]

Demo/Demo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from Home import views as Home_views
urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^account/',include("account.urls")),
    url(r'^pwd_reset/',include("password_reset.urls",namespace="pwd_reset",app_name="pwd_reset")),
    url(r'^BlogPost/',include("BlogPost.urls")),# import the BlogPost app
    url(r'^home/',Home_views.index,name="index"),
    url(r'^Article/',include("Articleapp.urls",namespace="Articleapp",app_name="Articleapp")),
    url(r'^Comment/',include("comment.urls")),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Demo/account/urls.py
from django.conf.urls import url
from . import views as account_views
from django.contrib.auth import views as auth_views
app_name = "account"

urlpatterns = [
    url(r'^activate/(?P<activate_code>.*)/$',account_views.ActivateUser,name="ActivateUser"),
    url(r'^register/$',account_views.register,name="register"),
    url(r'^login/$',auth_views.login,{"template_name":"account/login.html"},name="login"),
    url(r'^logout/$',auth_views.logout,{"template_name":"account/logout.html"},name="logout"),
    url(r'^password-change/$',auth_views.password_change,{"template_name":"account/password_change.html","post_change_redirect":"/account/password-change-done"},name="password_change"),
    url(r'^password-change-done/$',auth_views.password_change_done,{"template_name":"account/password_change_done.html"},name="password_change_done"),
    url(r'^AuthorArticle/(?P<user_id>\d+)/$',account_views.AuthorArticle,name="AuthorArticle"),
]

Demo/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>{% block title %} {% endblock %}</title>
    {% block Style %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/media.css' %}">
    <!-- 新 Bootstrap4 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/css/bootstrap.min.css">

    <!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
    <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>

    <!-- popper.min.js 用于弹窗、提示、下拉菜单 -->
    <script src="https://cdn.staticfile.org/popper.js/1.12.5/umd/popper.min.js"></script>

    <!-- 最新的 Bootstrap4 核心 JavaScript 文件 -->
    <script src="https://cdn.staticfile.org/twitter-bootstrap/4.1.0/js/bootstrap.min.js"></script>

    <!-- 引入字体图标文件 -->
    <link rel="stylesheet" href="https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css">

    <!-- 引用自己的Css -->
    <link rel="stylesheet" href="{% static 'css/StyleCss.css' %}">

    <!-- swifter 插件文件-->
    <link rel="stylesheet" href="{% static 'dist/css/swiper.min.css' %}">
    <script src="{% static 'dist/js/swiper.min.js' %}"></script>
    <!-- -->
    <!-- layer文件-->
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/OwnCss.js' %}"></script>
    <!-- end -->
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/csrf.js' %}"></script>
</head>
<body>
<div class="container-fluid">
{% block header %} {% endblock %}
{% block content %} {% endblock %}
{% block footer %} {% endblock %}
</div>
</body>
</html>

Demo/templates/footer.html
<footer class="text-center">
    <p>运营者邮箱:Masonluo918@gmail.com</p>
</footer>

Demo/templates/nav.html
{% load staticfiles %}

<nav class="navbar navbar-expand-sm bg-dark navbar-dark d-flex flex-row bg-secondary" style="padding:0; ">
    <div class="nav-left p-2" style="width:20%;">
        <a class="navbar-brand" href="/home/">
            <img class="img-fluid rounded-circle" src="{% static 'Image/logo.png' %}" alt="logo"
                 style="width: 100px; height: 50px;">
        </a>
    </div>
    <div class="nav-right" style="width:75%;">
        <ul class="navbar-nav p-2 d-flex flex-row-reverse">
            {% if user.is_authenticated %}
            <li class="nav-item dropdown p-2">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">{{
                    user.username}}
                </button>
                <div class="dropdown-menu">

                    <a class="dropdown-item" href="{% url 'account:password_change' %}">修改密码</a>
                    <a class="dropdown-item" href="{%  url 'account:logout' %}">退出登陆</a>
                    <a class="dropdown-item" href="{% url 'BlogPost:PostManage' %}">后台管理</a>
                    <!--<a class="dropdown-item" href="#">个人信息</a>-->
                </div>
            </li>
            {% else %}
            <li class="nav-item p-2">
                <button type="button" class="btn btn-primary"><a href="{% url 'account:login' %}" style="color:white;">登录 </a>
                </button>
            </li>
            <li class="nav-item p-2">
                <button type="button" class="btn btn-primary"><a href="{% url 'account:register' %}"
                                                                 style="color:white;">注册</a></button>
            </li>
            {% endif %}
        </ul>
    </div>
    <script type="text/javascript" src="{% static 'js/csrf.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/OwnCss.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
</nav>

Demo/templates/nav2.html
{% load staticfiles %}
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav  text-left">
        <li class="nav-item">
            <img class="rounded-circle" src="{% static 'Image/logo.png' %}" width="40%">
        </li>
        <li class="nav-item text-center text-item">
            <a href="/home">首页</a>
        </li>
         <li class="nav-item text-center text-item">
            <a href="javascript:" onclick="functionDoesNotbuild()">美图页面</a>
        </li>
    </ul>
    <div style="width:65%;"></div>
    <ul class="navbar-nav">
    <li class="nav-item text-center text-item">
            <a href="/home">首页</a>
        </li>
    </ul>
</nav>

Demo/templates/nav3.html
{% load staticfiles %}
<nav class="row bg-dark" style="margin:2px;">
    <div class="col-12 col-md-2 text-center">
        <img class="rounded-circle" src="{% static 'Image/logo.png' %}" height="65px;">
    </div>
    <div class="col-12 col-md-1 text-center text-item">
        <a href="/home">首页</a>
    </div>
    <div class="col-12 col-md-2 text-center text-item">
        <a href="javascript:" onclick="functionDoesNotbuild()">美图页面</a>
    </div>
    {% if user.is_authenticated %}
    <div class="col-md-5"></div>
    <div class="col-md-2 text-center text-item dropdown">
        <div class="row text-center">
            <div class="col-md-5" style="padding:0;">
                <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">{{ user.username }}</button>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'account:password_change' %}">修改密码</a>
                    <a class="dropdown-item" href="{%  url 'account:logout' %}">退出登陆</a>
                    <a class="dropdown-item" href="{% url 'BlogPost:PostManage' %}">后台管理</a>
                    <!--<a class="dropdown-item" href="#">个人信息</a>-->
                </div>
            </div>
            {% else %}
            <div class="col-md-5" style="padding:0;"></div>
            <div class="col-md-1 text-center text-item" style="padding:2px;">
                <a href="{% url 'account:login' %}">
                    <button class="btn btn-primary">登录</button>
                </a>
            </div>
            <div class="col-md-1 text-center text-item" style="padding:2px;">
                <a href="{% url 'account:register' %}">
                    <button class="btn btn-primary">注册</button>
                </a>
            </div>
        </div>
    </div>
    {% endif %}
    <script type="text/javascript" src="{% static 'js/csrf.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/OwnCss.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
</nav>

Demo/templates/paginator.html
<div class="pagination">
    <span class="step-link">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}">上一页</a>
        {% endif %}
        <span class="current">
        Page {{ page.number }}/{{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">下一页</a>
    {% endif %}

    </span>

</div>