Demo/Articleapp/urls.py
from django.conf.urls import url
from . import views as Article_views

urlpatterns = [
    url(r'^ArticleDetail/(?P<articleId>\d+)/(?P<articleSlug>[-\w]+)/$',Article_views.ArticleDetail,name="ArticleDetail"),
    url(r'^LikeArticle/$',Article_views.like_article,name="like_article"),
]

Demo/Demo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from Home import views as Home_views
urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^account/',include("account.urls")),
    url(r'^pwd_reset/',include("password_reset.urls",namespace="pwd_reset",app_name="pwd_reset")),
    url(r'^BlogPost/',include("BlogPost.urls")),# import the BlogPost app
    url(r'^home/',Home_views.index,name="index"),
    url(r'^Article/',include("Articleapp.urls",namespace="Articleapp",app_name="Articleapp")),
    url(r'^Comment/',include("comment.urls")),
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Demo/account/urls.py
from django.conf.urls import url
from . import views as account_views
from django.contrib.auth import views as auth_views
app_name = "account"

urlpatterns = [
    url(r'^activate/(?P<activate_code>.*)/$',account_views.ActivateUser,name="ActivateUser"),
    url(r'^register/$',account_views.register,name="register"),
    url(r'^login/$',auth_views.login,{"template_name":"account/login.html"},name="login"),
    url(r'^logout/$',auth_views.logout,{"template_name":"account/logout.html"},name="logout"),
    url(r'^password-change/$',auth_views.password_change,{"template_name":"account/password_change.html","post_change_redirect":"/account/password-change-done"},name="password_change"),
    url(r'^password-change-done/$',auth_views.password_change_done,{"template_name":"account/password_change_done.html"},name="password_change_done"),
    url(r'^AuthorArticle/(?P<user_id>\d+)/$',account_views.AuthorArticle,name="AuthorArticle"),
]

Demo/templates/Article/detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
{{ Article.title }}
{% endblock %}
{% block content %}
{% with total_likes=Article.users_like.count %}
{% with total_read=Article.users_read.count %}
<div class="container-fluid">
    {% include "nav3.html" %}
</div>
<div class="row text-left" style="margin-top:10px;">
    <div class="col-12 col-sm-12 col-md-3 border AuthorDetail text-center">
        <div class="author-name">{{ Article.author.username}}的其他文章</div>
        <div class="ArticleList">
            {% for article in Articles %}
            {% if article != Article %}
            <a href="{{ article.get_detail_url }}" style="color:black;font-family: 华文新魏;">
                <div class="Article text-left">
                    <div class="title">
                        <h4>{{ article.title }}</h4>
                    </div>
                    <div class="author_time" style="color:#8F938F;">
                        {{ article.author.username }} | {{ article.column }} | {{ article.publish_time }}
                    </div>
                </div>
            </a>
            {% endif %}
            {% endfor %}
        </div>

        <div class="author-name">点赞最多文章</div>
        <div class="ArticleList">
            {% for article in UserlikesMoreArticle %}
            {% if article != Article %}
            <a href="{{ article.get_detail_url }}" style="color:black;font-family: 华文新魏;">
                <div class="Article text-left">
                    <div class="title">
                        <h4>{{ article.title }}</h4>
                    </div>
                    <div class="author_time" style="color:#8F938F;">
                        {{ article.author.username }} | {{ article.column }} | {{ article.publish_time }}
                    </div>
                </div>
            </a>
            {% endif %}
            {% endfor %}
        </div>
        <div class="author-name">阅读最多文章</div>
        <div class="ArticleList">
            {% for article in UserReadsMoreArticle %}
            {% if article != Article %}
            <a href="{{ article.get_detail_url }}" style="color:black;font-family: 华文新魏;">
                <div class="Article text-left">
                    <div class="title">
                        <h4>{{ article.title }}</h4>
                    </div>
                    <div class="author_time" style="color:#8F938F;">
                        {{ article.author.username }} | {{ article.column }} | {{ article.publish_time }}
                    </div>
                </div>
            </a>
            {% endif %}
            {% endfor %}
        </div>
    </div>
    <div class="col-12 col-sm-12 col-md-8 ArticleArea">
        <div>
            <header>
                <h2>{{ Article.title }}</h2>
                <p>{{ Article.publish_time}} <a href="#">{{ Article.author.username }}</a> {{ Article.column }}
                    {% if user.authenticated %}
                    <a href="javascript:" onclick="like_article({{ Article.id}} , 'like')" class="fa fa-thumbs-o-up"
                       style="font-size:1.2rem;"></a>
                    <a href="javascript:" onclick="like_article({{ Article.id}},'unlike')" class="fa fa-thumbs-o-down"
                       style="font-size:1.2rem;"></a>
                    {% else %}
                    <a href="javascript:" onclick="layer.msg('请先登录');" class="fa fa-thumbs-o-up"
                       style="font-size:1.2rem;"></a>
                    <a href="javascript:" onclick="layer.msg('请先登录');" class="fa fa-thumbs-o-down"
                       style="font-size:1.2rem;"></a>
                    {% endif %}
                    <span class="fa fa-thumbs-up" style="margin-left:20px;color:green;">{{ total_likes }} like{{ total_likes | pluralize }}</span>
                    <span class="fa fa-eye" style="margin-left:20px;color:green;">{{ total_read }} like{{ total_read | pluralize }}</span>
                </p>
            </header>
            <link rel="stylesheet" href="{% static 'editor/css/editormd.preview.css' %}">
            <div id="editormd-view" style="padding:0;font-size:1.0rem;">
                <textarea id="append-test" style="display: none;" required>
                    {{ Article.body }}
                </textarea>
            </div>
            <footer class="text-center">
                <p>PS:转载请经过作者许可，并注明出处和来源，谢谢。</p>
            </footer>
        </div>
    </div>
</div>
{% if user.is_authenticated %}

<div class="Comment row border">
    <div class="new">
    <textarea id="NewComment" class="NewComment" placeholder="&nbsp&nbsp请发表你的评论~">
    </textarea>
        <button type="button" class="btn btn-outline-info float-right" onclick="SubmitNewComment(this)">发表</button>
    </div>
</div>
{% else %}
<div class="text-center" style="width:100%;font-family: 华文新魏;font-size:1.2rem;"><a
        href="{% url 'account:login' %}">登录</a>后才能再评论哦
</div>
{% endif %}
<h5 class="border-dark text-center" style="width:100%;font-family: 华文新魏;font-size:1.6rem;">评论区</h5>
<div class="OldComment">
    {% for comment in Comments %}
    <div class="articleComment">
        <p>{{ comment.user}} | {{ comment.comment_time|date }}</p>
        <div class="text-left">
            {{ comment.body }}
        </div>
        <a href="javascript:" onclick="apply(this,{{ comment.id }})">回复</a>
    </div>
    {% for item in comment.child_comment.all %}
    <div class="childComment">
        <p>{{ item.user}} | {{ item.comment_time|date }}</p>
        <div class="text-left">
            {{ item.body }}
        </div>
        <a href="javascript:" onclick="apply(this,{{ comment.id }})">回复</a>
    </div>
    <hr style="width:90%;margin:0 auto;">
    {% endfor %}
    <hr style="width:90%;margin:0 auto;">
    {% endfor %}
</div>
<!--<div id="SOHUCS" ></div>-->
<!--<script charset="utf-8" type="text/javascript" src="https://changyan.sohu.com/upload/changyan.js" ></script>-->
<!--<script type="text/javascript">-->
<!--window.changyan.api.config({-->
<!--appid: 'cytNoLI57',-->
<!--conf: 'prod_40a299e26aa7f379e20bdcc5f8daa581'-->
<!--});-->
<!--</script>-->
<script type="text/javascript" src="{% static 'js/csrf.js' %}"></script>
<script type="text/javascript" src="{% static 'editor/lib/marked.min.js' %}"></script>
<script type="text/javascript" src="{% static 'editor/lib/prettify.min.js' %}"></script>
<script type="text/javascript" src="{% static 'editor/lib/raphael.min.js' %}"></script>
<script type="text/javascript" src="{% static 'editor/lib/underscore.min.js' %}"></script>
<script type="text/javascript" src="{% static 'editor/lib/sequence-diagram.min.js' %}"></script>
<script type="text/javascript" src="{% static 'editor/lib/flowchart.min.js' %}"></script>
<script type="text/javascript" src="{% static 'editor/lib/jquery.flowchart.min.js' %}"></script>
<script type="text/javascript" src="{% static 'editor/editormd.js' %}"></script>

<script type="text/javascript">

    var is_activate = 1;

    $(function () {
        editormd.markdownToHTML("editormd-view", {
            htmlDecode: "style,script,iframe",
            emoji: true,
            taskList: true,
            tex: true,
            flowChart: true,
            sequenceDiagram: true,
        });
    });

    function SubmitNewComment(the, boolean) {
        var body = $("#NewComment").val();
        var IsNewComment;
        $.ajax({
            type: "POST",
            data: {"body": body, "IsNewComment": "True"},
            url: "{% url 'Articleapp:ArticleDetail' Article_id ArticleSlug %}",
            success: function (e) {
                if (e == "1") {

                    layer.msg('评论成功', {time: 1000}, function () {
                        window.location.reload();
                    });
                }
                else {
                    layer.msg("评论失败");
                }
            },
        });
    }

    function apply(the, Parent_id) {

        if (is_activate == 1) {
            $(the).after("<div class='newChild'><textarea id='NewChildComment' class='NewChildComment' placeholder='&nbsp&nbsp请发表你的评论~'></textarea><button type='button' class='btn btn-outline-info float-right' onclick='SubmitNewChildComment(this," + Parent_id + ")'>发表</button></div>");
            is_activate = 0;
        }
    }

    function SubmitNewChildComment(the, Parent_id) {
        var body = $("#NewChildComment").val();
        $.ajax({
            type: "POST",
            data: {"ParentCommentId": Parent_id, "body": body, "IsNewComment": "False"},
            url: "{% url 'Articleapp:ArticleDetail' Article_id ArticleSlug %}",
            success: function (e) {
                if (e == "1") {
                    layer.msg('评论成功', {time: 1000}, function () {
                        window.location.reload();
                    });
                }
                else {
                    layer.msg("评论失败");
                }
            },
        });
    }

    function like_article(artilce_id, action) {
        $.ajax({
            type: "POST",
            data: {"ArticleId": artilce_id, "action": action},
            url: "{% url 'Articleapp:like_article' %}",
            success: function (e) {
                if (e == "1") {
                    layer.msg("谢谢点赞", {time: 500}, function () {
                        window.location.reload();
                    })
                }
                else {
                    layer.msg("我会继续努力！", {time: 500}, function () {
                        window.location.reload();
                    })
                }
            },
        });
    }
</script>
{% endwith %}
{% endwith %}
{% endblock %}